In [1]:
%matplotlib ipympl
import cv2
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from pytransform3d.rotations import *

In [2]:
R = np.array([[ 1.,          0.,          0.,        ],
 [ 0.,          0.70710678,  0.70710678],
 [ 0.,         -0.70710678,  0.70710678]])
t = np.array([0.5, 1, -0.32])

In [3]:
R.shape

(3, 3)

In [4]:
def to_twist(R, t):
    r, _ = cv2.Rodrigues(R)
    twist = np.zeros((6,))
    twist[:3] = r.reshape(3,)
    twist[3:] = t.reshape(3,)
    return twist

def from_twist(twist):
    r = twist[:3]
    t = twist[3:]
    R, _ = cv2.Rodrigues(r)
    return R, t

In [5]:
print(R, t)
twist = to_twist(R, t)
print(twist)
R, t = from_twist(twist)
print(R, t)

[[ 1.          0.          0.        ]
 [ 0.          0.70710678  0.70710678]
 [ 0.         -0.70710678  0.70710678]] [ 0.5   1.   -0.32]
[-0.78539816  0.          0.          0.5         1.         -0.32      ]
[[ 1.          0.          0.        ]
 [ 0.          0.70710678  0.70710678]
 [ 0.         -0.70710678  0.70710678]] [ 0.5   1.   -0.32]
