In [77]:
%matplotlib ipympl
import cv2
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from pytransform3d.rotations import *

In [78]:
import pickle
data = pickle.load(open("DroneMapper/data.pkl", "rb"))
pts1 = data["last_pts"][0]
pts2 = data["current_pts"][0]
# pose of second camera relative to first camera
R = data["pose_R"]
t = data["pose_t"].reshape(3,)

In [66]:
# camera matrix
w = 1920
h = 1080
fx = 1184.51770
fy = 1183.63810
cx = 978.30778
cy = 533.85598
# camera matrix
K = np.array([[fx, 0, cx], [0, fy, cy], [0, 0, 1]])
dist_coeffs = np.array([-0.01581, 0.01052, -0.00075, 0.00245, 0.00000])

In [67]:
# create projection matrices
proj_matrix1 = np.array([[1, 0, 0, 0],[0, 1, 0, 0],[0, 0, 1, 0]])
proj_matrix2 = np.zeros((3, 4))
proj_matrix2[:, :3] = R
proj_matrix2[:, -1] = t
proj_matrix1 = np.matmul(K, proj_matrix1)
proj_matrix2 = np.matmul(K, proj_matrix2)

In [68]:
proj_matrix1

array([[1.1845177e+03, 0.0000000e+00, 9.7830778e+02, 0.0000000e+00],
       [0.0000000e+00, 1.1836381e+03, 5.3385598e+02, 0.0000000e+00],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, 0.0000000e+00]])

In [69]:
proj_matrix2

array([[ 1.17881857e+03, -2.07477566e+00,  9.85165355e+02,
         7.58200734e+01],
       [-5.16180359e+00,  1.18138248e+03,  5.38804364e+02,
         1.22484395e+03],
       [-5.80327284e-03, -4.20228711e-03,  9.99974331e-01,
         8.53154185e-02]])

In [70]:
pts = cv2.triangulatePoints(proj_matrix1, proj_matrix2, pts1.T, pts2.T).reshape(-1, 4)

In [71]:
pts = cv2.convertPointsFromHomogeneous(pts).reshape(-1, 3)

In [76]:
pts

array([[-1.40927046, -1.57137809, -2.09440025],
       [-1.53452458, -1.88051861, -1.82899073],
       [ 1.03870196,  0.85903676,  0.48402249],
       ...,
       [ 5.51969547,  1.07468217,  2.13239235],
       [ 0.26600276,  0.25655879,  0.25867327],
       [ 0.45922068,  0.46500108,  0.62653361]])

In [73]:
fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')
ax.scatter(pts[:, 0], pts[:, 1], pts[:, 2])
plot_basis(ax, np.eye(3), np.zeros(3))
plot_basis(ax, R, t)
ax.set_xlim([-1,1])
ax.set_ylim([-1,1])
ax.set_zlim([-10,10])
plt.show()

FigureCanvasNbAgg()